version: '3.7'



services:
  ca.org1.com.tw:
    container_name: ca.org1.com.tw
    image: hyperledger/fabric-ca:latest
    labels:
      service: hyperledger-fabric
      type: ca
    ports:
      - 2054:2054
    command: sh -c 'fabric-ca-server start'
    volumes:
      - ./org1.com.tw/ca:/etc/hyperledger/fabric-ca-server
    networks:
      - fabric-ca

  tls.org1.com.tw:
    container_name: tls.org1.com.tw
    image: hyperledger/fabric-ca:latest
    labels:
      service: hyperledger-fabric
      type: ca.tls
    ports:
      - 1154:1154
    command: sh -c 'fabric-ca-server start'
    volumes:
       - ./org1.com.tw/tls:/etc/hyperledger/fabric-ca-server
    networks:
      - fabric-ca

  ca.org2.com.tw:
    container_name: ca.org2.com.tw
    image: hyperledger/fabric-ca:latest
    labels:
      service: hyperledger-fabric
      type: ca
    ports:
      - 3054:3054
    command: sh -c 'fabric-ca-server start'
    volumes:
      - ./org2.com.tw/ca:/etc/hyperledger/fabric-ca-server
    networks:
      - fabric-ca

  tls.org2.com.tw:
    container_name: tls.org2.com.tw
    image: hyperledger/fabric-ca:latest
    labels:
      service: hyperledger-fabric
      type: ca.tls
    ports:
      - 3154:3154
    command: sh -c 'fabric-ca-server start'
    volumes:
       - ./org2.com.tw/tls:/etc/hyperledger/fabric-ca-server
    networks:
      - fabric-ca

networks:
  fabric-ca: