version: '3'

networks:
  ca:
    name: ca_network

services:
  ca.orderer.com:
    image: hyperledger/fabric-ca:latest
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.orderer.com
      - FABRIC_CA_SERVER_TLS_ENABLE=true
      - FABRIC_CA_SERVER_PORT=1054
      - FABRIC_CA_SERVER_OPERATIONS_LISTENADDRESS=0.0.0.0:11054
    ports:
      - "1054:1054"
      - "11054:11054"
    command: sh -c 'fabric-ca-server start -d'
    volumes:
      - ./config/orderer.com/ca:/etc/hyperledger/fabric-ca-server
    container_name: ca.orderer.com
    networks:
      - ca

  tls.orderer.com:
    image: hyperledger/fabric-ca:latest
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=tls.orderer.com
      - FABRIC_CA_SERVER_TLS_ENABLE=true
      - FABRIC_CA_SERVER_PORT=1154
      - FABRIC_CA_SERVER_OPERATIONS_LISTENADDRESS=0.0.0.0:11154
    ports:
      - "1154:1154"
      - "11154:11154"
    command: sh -c 'fabric-ca-server start -d'
    volumes:
      - ./config/orderer.com/tls:/etc/hyperledger/fabric-ca-server
    container_name: tls.orderer.com
    networks:
      - ca

  ca.nchc.org.tw:
    image: hyperledger/fabric-ca:latest
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.nchc.org.tw
      - FABRIC_CA_SERVER_TLS_ENABLE=true
      - FABRIC_CA_SERVER_PORT=2054
      - FABRIC_CA_SERVER_OPERATIONS_LISTENADDRESS=0.0.0.0:12054
    ports:
      - "2054:2054"
      - "12054:12054"
    command: sh -c 'fabric-ca-server start -d'
    volumes:
      - ./config/nchc.org.tw/ca:/etc/hyperledger/fabric-ca-server
    container_name: ca.nchc.org.tw
    networks:
      - ca

  tls.nchc.org.tw:
    image: hyperledger/fabric-ca:latest
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=tls.nchc.org.tw
      - FABRIC_CA_SERVER_TLS_ENABLE=true
      - FABRIC_CA_SERVER_PORT=2154
      - FABRIC_CA_SERVER_OPERATIONS_LISTENADDRESS=0.0.0.0:12154
    ports:
      - "2154:2154"
      - "12154:12154"
    command: sh -c 'fabric-ca-server start -d'
    volumes:
      - ./config/nchc.org.tw/tls:/etc/hyperledger/fabric-ca-server
    container_name: tls.nchc.org.tw
    networks:
      - ca

  ca.biobank.org.tw:
    image: hyperledger/fabric-ca:latest
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.biobank.org.tw
      - FABRIC_CA_SERVER_TLS_ENABLE=true
      - FABRIC_CA_SERVER_PORT=3054
      - FABRIC_CA_SERVER_OPERATIONS_LISTENADDRESS=0.0.0.0:13054
    ports:
      - "3054:3054"
      - "13054:13054"
    command: sh -c 'fabric-ca-server start -d'
    volumes:
      - ./config/biobank.org.tw/ca:/etc/hyperledger/fabric-ca-server
    container_name: ca.biobank.org.tw
    networks:
      - ca

  tls.biobank.org.tw:
    image: hyperledger/fabric-ca:latest
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=tls.biobank.org.tw
      - FABRIC_CA_SERVER_TLS_ENABLE=true
      - FABRIC_CA_SERVER_PORT=3154
      - FABRIC_CA_SERVER_OPERATIONS_LISTENADDRESS=0.0.0.0:13154
    ports:
      - "3154:3154"
      - "13154:13154"
    command: sh -c 'fabric-ca-server start -d'
    volumes:
      - ./config/biobank.org.tw/tls:/etc/hyperledger/fabric-ca-server
    container_name: tls.biobank.org.tw
    networks:
      - ca